<?php

Class Apartment extends Room {

    public function __construct(int $roomNumber, int $price)
    {
        $this->setBedCount(4);
        $this->setRoomType('Diamond');
        $this->setHasRestroom('has restroom');
        $this->setHasBalcony('has balcony');
        $this->setExtras('TV, air-conditioner, refrigerator, kitchen box, mini-bar,bathub, wi-fi');
        $this->setPrice($price);
        $this->setRoomNumber($roomNumber);
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}