<?php

Class Bedroom extends Room {

    public function __construct(int $roomNumber, int $price)
    {
        $this->setBedCount(2);
        $this->setRoomType('Gold');
        $this->setHasRestroom('has restroom');
        $this->setHasBalcony('has balcony');
        $this->setExtras('TV, air-conditioner,refrigerator,mini-bar,bathub');
        $this->setPrice($price);
        $this->setRoomNumber($roomNumber);
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}