<?php

Class SingleRoom extends Room {

    public function __construct(int $roomNumber, int $price)
    {
        $this->setBedCount(1);
        $this->setRoomType('Standart');
        $this->setHasRestroom('has restroom');
        $this->setHasBalcony('no balcony');
        $this->setExtras('TV, air-conditioner');
        $this->setRoomNumber($roomNumber);
        $this->setPrice($price);
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

}